# Generated by Django 5.0.3 on 2024-03-27 20:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo del post')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion del post')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido del post')),
                ('imagen', models.URLField(max_length=250)),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de publicacion')),
                ('estado', models.BooleanField(verbose_name='Publicado/No publicado')),
                ('slug', models.SlugField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
